spring:
  application:
    name: eureka-client-01
server:
  port: 8763
eureka:
  client:
    server-url:
      # 注册地址
      defaultZone: http://localhost:8761/eureka/
    #是否显示注册信息
    register-with-eureka: true
  server:
    #自我保护
    enable-self-preservation: true
logging:
  level:
    root: info

