spring:
  application:
    name: zuul-01
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8762
#eureka:
#  client:
#    server-url:
      # 注册地址
#      defaultZone: http://localhost:8761/eureka/
    #是否显示注册信息
#    register-with-eureka: true
logging:
  level:
    root: error
zuul:
  routes:
    uuu:
      path: /api/**
      serviceId: nacos-client
    #testService:
     # path: /api2/**
     # url: http://localhost:8763/
management:
  endpoints:
    web:
      exposure:
        include: routes,filters